# Generated by Django 5.2 on 2025-07-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trizync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(),
        ),
    ]
