# Generated by Django 5.2 on 2025-07-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trizync', '0003_account_project_is_completed_projectexpanse_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexpanse',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projectpayment',
            name='date',
            field=models.DateField(),
        ),
    ]
