# Generated by Django 5.2 on 2025-05-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='custoer_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
