# Generated by Django 5.2 on 2025-05-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_license_custoer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='custoer_name',
            new_name='customer_name',
        ),
    ]
