# Generated by Django 5.2 on 2025-05-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_custoer_name_license_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
    ]
