# Generated by Django 5.2 on 2025-05-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_license_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathaoCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('token_expiry_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
