# Generated by Django 5.2 on 2025-06-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pathaocredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
                ('event_name', models.CharField(max_length=255)),
            ],
        ),
    ]
