# Generated by Django 5.2 on 2025-06-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
