# Generated by Django 5.2 on 2025-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_messengeruser_trizyncservice_usermessage_userbudget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='source',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
