# Generated by Django 5.2 on 2025-06-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_usermessage_source_usermessage_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='FacebookEvent',
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.RemoveField(
            model_name='userwebsite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbudget',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userservice',
            name='user',
        ),
        migrations.DeleteModel(
            name='PathaoCredential',
        ),
        migrations.RemoveField(
            model_name='userservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='userbudget',
            name='message',
        ),
        migrations.RemoveField(
            model_name='userwebsite',
            name='message',
        ),
        migrations.RemoveField(
            model_name='userservice',
            name='message',
        ),
        migrations.DeleteModel(
            name='MessengerUser',
        ),
        migrations.DeleteModel(
            name='TrizyncService',
        ),
        migrations.DeleteModel(
            name='UserBudget',
        ),
        migrations.DeleteModel(
            name='UserWebsite',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
        migrations.DeleteModel(
            name='UserService',
        ),
    ]
