# Generated by Django 5.2 on 2025-06-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_usermessage_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengeruser',
            name='auto_message',
            field=models.BooleanField(default=True),
        ),
    ]
