# Generated by Django 5.2 on 2025-06-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_messengeruser_auto_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengeruser',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
