# Generated by Django 5.2 on 2025-06-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_geminiaccesstoken_pageaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMSystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(default="You are Trizync Solution's intelligent virtual assistant.")),
            ],
        ),
    ]
