# Generated by Django 5.2 on 2025-07-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_llmsystemprompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messengeruser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='messengeruser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='messengeruser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='messengeruser',
            name='phone',
        ),
        migrations.AddField(
            model_name='messengeruser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
