# Generated by Django 5.2 on 2025-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_userservice_service_useraddress_useremail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZyncopsPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='zyncops')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
