# Generated by Django 5.2 on 2025-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_zyncopsplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengeruser',
            name='trial_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
