# Generated by Django 5.2 on 2025-07-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_messengeruser_trial_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
