# Generated by Django 5.2 on 2025-07-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_license_email_license_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookEventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_request', models.CharField(max_length=255)),
                ('standard_event', models.CharField(max_length=255)),
                ('fbtrace_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('request_data', models.JSONField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.license')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.facebookevent')),
            ],
        ),
    ]
