# Generated by Django 5.2 on 2025-07-06 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_facebookeventrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookeventrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 6, 15, 58, 2, 733915, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
